### ISSUE TITLE
Highpass Butterworth filter frequency issue

### ISSUE THREAD

**Issue by romancfischer** [PaulBatchelor/Soundpipe#111] opened 2019-05-19 14:30 UTC
hi Paul, first of all: thanks for the amazing library!

I have an issue with sp_buthp_compute when the frequency parameter is really low, let's say at 20 Herz. It creates weird noises / almost like white noise or crackling. I tried it on several sources and the problem is always there. what can I do in order to prevent this from happening?

**Comment by PaulBatchelor** [comment] 2019-05-19 19:10
I imagine the noise you are hearing could be a result of a floating point rounding error. 20Hz is an unusually low value to use for a butterworth highpass filter. It's practically a DC blocker at that point (if you are using this as a DC blocker, there is one in soundpipe you can use called `dcblock`.) If I may ask, what are you using it for?

Unfortunately, there's not a great deal I can do to fix the crackles. It's not a bug with the algorithm, but with how computers represent numbers digitally.

I have a few suggestions:

If you are using a local copy of Soundpipe, you can change the precision from floating point to double by defining the `SPFLT` macro to be `double`. That might make it go away.

You can also check out `atone`, the other highpass filter in SP. That design is a one pole filter (buthp is 2-pole), which I believe should make it a bit more resilient to floating-point related numerical errors.

Other than that, I would probably just see if you can live with setting the cutoff to be a bit higher.

**Comment by romancfischer** [comment] 2019-05-19 23:42
thanks for your quick reply.
I have effect sliders for touch, so the idea is, that the lowpass is either softly coming in from zero or bypassed when zero.

I‘ve tried atone before but didn‘t get the desired result.
I also tried stepping in on a higher frequency but that doesn‘t feel very natural.

my app is based on float, not double precision anyway.. hmm.. I guess it would still make sense to give it a try though?

I‘ll read up on the dc block filter and try the things you mentioned above..
thanks!

**Comment by PaulBatchelor** [comment] 2019-05-20 00:41
Have you tried adding a small crossfade between the filtered and unfiltered signal when it is turned on? That could smooth things over.

**Comment by romancfischer** [comment] 2019-05-20 09:58
yeah I actually thought about that too.. I did that on other effects, maybe it will work. I'll give it a try and will let you know. thanks!

**Comment by romancfischer** [comment] 2019-05-20 13:52
so crassfading didn't solve the problem, but I just duplicated the module and changed all SPFLOATs to doubles and that did the trick! :))) thx

**Comment by PaulBatchelor** [comment] 2019-05-20 16:17
No problem! Closing this issue now.

**Closed by PaulBatchelor** 2019-05-20 16:17 UTC
